### ISSUE TITLE
Add integration testing showcase

### ISSUE THREAD

**Issue by daniellavoie** [daniellavoie/confluent-microservices#8]

**Comment by louisthomas** [comment]
With Kafka test containers?

https://www.testcontainers.org/modules/kafka/

**Comment by daniellavoie** [comment]
The overall strategy involves testing each microservice contracts against a Kafka cluster separately. Each microservice is packaged with standalone integration tests that interract with either their Rest API or through a Kafka consumer or producer. This ensure that the services behaves as they should without any dependency from other services.
